name: Format Code with Black

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:  # Run the workflow on pull requests

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"  # Replace with your Python version

    - name: Install Black
      run: pip install black

    - name: Run Black
      run: black .
